Update actions

diff --git a/.github/workflows/recipe_flato13ipcc_figures_938_941_cmip3.yml b/.github/workflows/recipe_flato13ipcc_figures_938_941_cmip3.yml
--- a/.github/workflows/recipe_flato13ipcc_figures_938_941_cmip3.yml
+++ b/.github/workflows/recipe_flato13ipcc_figures_938_941_cmip3.yml
@@ -37,3 +37,32 @@ jobs:
           script: |
             cd ${{secrets.GADI_SCRIPTS_DIR}}/../ESMValTool/jobs
             qsub launch_recipe_flato13ipcc_figures_938_941_cmip3.pbs
+      - name: Get output log
+        uses: nicklasfrahm/scp-action@main
+        with:
+          direction: download
+          host: gadi.nci.org.au
+          username: $${{secrets.GADI_USER}}
+          insecure_ignore_fingerprint: true
+          key: $${{secrets.DEPLOY_KEY}}
+          source: $${{secrets.GADI_SCRIPTS_DIR}}/../ESMValTool/logs/recipe_flato13ipcc_figures_938_941_cmip3.out
+          target: log.txt
+      - name: Upload log as artifact
+        if: ${{ github.event.workflow_run.name == 'Run all recipes' || ( github.event.workflow_run.name == 'Run all failed' && steps.latest-workflow-status.outputs.result != 'success' ) || github.event_name == 'workflow_dispatch' }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: output_log
+          path: log.txt
+      - name: Create Issue if fails
+        if: ${{ failure() }}
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        run: |
+          github_id=$(gh api --header "Accept: application/vnd.github+json" --header 'X-GitHub-Api-Version:2022-11-28' --method GET /repos/ACCESS-NRI/ESMValTool-workflow/issues?state=open | jq '.[] | select(.title == "Recipe: recipe_flato13ipcc_figures_938_941_cmip3 failing") | .number')
+          if [ -z "$github_id" ]
+          then
+            gh api --header "Accept: application/vnd.github+json" --header 'X-GitHub-Api-Version:2022-11-28' --method POST /repos/ACCESS-NRI/ESMValTool-workflow/issues -f title="Recipe: recipe_flato13ipcc_figures_938_941_cmip3 failing" -f body="Please check log in action workflow"
+          else
+            # gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ACCESS-NRI/ESMValTool-workflow/issues/$github_id/comments -f body="Still failing"
+          fi
+          
