Test existing issue

diff --git a/.github/workflows/recipe_arctic_ocean.yml b/.github/workflows/recipe_arctic_ocean.yml
--- a/.github/workflows/recipe_arctic_ocean.yml
+++ b/.github/workflows/recipe_arctic_ocean.yml
@@ -26,8 +26,8 @@ jobs:
             })
             return runs.data.workflow_runs[1].conclusion
           result-encoding: string
-      - name: Run recipe_arctic_ocean
-        if: ${{ github.event.workflow_run.name == 'Run all recipes' || ( github.event.workflow_run.name == 'Run all failed' && steps.latest-workflow-status.outputs.result != 'success' ) || github.event_name == 'workflow_dispatch' }}
+      #- name: Run recipe_arctic_ocean
+      #  if: ${{ github.event.workflow_run.name == 'Run all recipes' || ( github.event.workflow_run.name == 'Run all failed' && steps.latest-workflow-status.outputs.result != 'success' ) || github.event_name == 'workflow_dispatch' }}
         #uses: appleboy/ssh-action@v0.1.7
         #with:
         #  host: gadi.nci.org.au
@@ -37,7 +37,6 @@ jobs:
         #  script: |
         #    cd ${{secrets.GADI_SCRIPTS_DIR}}/../ESMValTool/jobs
         #    qsub launch_recipe_arctic_ocean.pbs
-        run: exit 1
       - name: copy file via ssh password
         if: ${{ github.event.workflow_run.name == 'Run all recipes' || ( github.event.workflow_run.name == 'Run all failed' && steps.latest-workflow-status.outputs.result != 'success' ) || github.event_name == 'workflow_dispatch' }}
         uses: appleboy/scp-action@v0.1.4
@@ -46,17 +45,25 @@ jobs:
           username: ${{secrets.GADI_USER}}
           key: ${{secrets.DEPLOY_KEY}}
           source: ${{secrets.GADI_SCRIPTS_DIR}}/../ESMValTool/logs/recipe_arctic_ocean.out
-          target: log.txt
+          target: .
       - name: Upload log as artifact
         if: ${{ github.event.workflow_run.name == 'Run all recipes' || ( github.event.workflow_run.name == 'Run all failed' && steps.latest-workflow-status.outputs.result != 'success' ) || github.event_name == 'workflow_dispatch' }}
         uses: actions/upload-artifact@v3
         with:
           name: output_log
           path: log.txt
+      - name: fail
+        run: exit 1
       - uses: actions/checkout@v3
       - name: Step To run on failure
         if: ${{ failure() }}
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          gh api --header "Accept: application/vnd.github+json" --header 'X-GitHub-Api-Version:2022-11-28' --method POST /repos/ACCESS-NRI/ESMValTool-workflow/issues -f title="Created with the REST API" -f body="This is a test issue created by the REST API"
+          github_id=$(gh api --header "Accept: application/vnd.github+json" --header 'X-GitHub-Api-Version:2022-11-28' --method GET /repos/ACCESS-NRI/ESMValTool-workflow/issues?state=open | jq '.[] | select(.title == "Created with the REST API") | .number')
+          if [ -z "$github_id" ]
+          then
+            gh api --header "Accept: application/vnd.github+json" --header 'X-GitHub-Api-Version:2022-11-28' --method POST /repos/ACCESS-NRI/ESMValTool-workflow/issues -f title="Created with the REST API" -f body="This is a test issue created by the REST API"
+          else
+            gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/ACCESS-NRI/ESMValTool-workflow/issues/$github_id/comments -f body="$(cat log.txt)"
+          fi
